import Syntax from "./syntax-type";

export const KEYWORDS = {
  protected: Syntax.Protected,
  private: Syntax.Private,
  package: Syntax.Package,
  use: Syntax.Use,
  from: Syntax.From,
  in: Syntax.In,
  is: Syntax.Is,
  typeof: Syntax.TypeOf,
  new: Syntax.New,
  class: Syntax.Class,
  mixin: Syntax.Mixin,
  interface: Syntax.Interface,
  return: Syntax.Return,
  break: Syntax.Break,
  next: Syntax.Next,
  and: Syntax.AmpersandAmpersand,
  or: Syntax.PipePipe,
  not: Syntax.Bang,
  fn: Syntax.Function,
  if: Syntax.If,
  every: Syntax.Every,
  while: Syntax.While,
  unless: Syntax.Unless,
  until: Syntax.Until,
  else: Syntax.Else,
  mut: Syntax.Mut,
  undefined: Syntax.Undefined,
  null: Syntax.Null
}