enum Syntax {
  INT,
  FLOAT,
  STRING,
  BOOLEAN,
  FUNCTION,

  INT_TYPE,
  FLOAT_TYPE,
  STRING_TYPE,
  BOOLEAN_TYPE,
  VOID_TYPE,
  NULL, UNDEFINED,

  IDENTIFIER,
  LPAREN, RPAREN,
  LBRACKET, RBRACKET,
  LBRACE, RBRACE,
  DOT, COLON,
  LT, GT, LTE, GTE,// <, >, <=, >=
  PLUS, MINUS,
  STAR, SLASH, SLASH_SLASH,
  CARAT, PERCENT,
  PLUS_EQUAL, MINUS_EQUAL,
  STAR_EQUAL, SLASH_EQUAL,
  CARAT_EQUAL, PERCENT_EQUAL,
  PLUS_PLUS, MINUS_MINUS,
  BANG,
  HASHTAG,
  EQUAL, EQUAL_EQUAL, BANG_EQUAL,

  EOF
}

export default Syntax;