enum Syntax {
  INT,
  FLOAT,
  STRING,
  BOOLEAN,
  INT_TYPE,
  FLOAT_TYPE,
  STRING_TYPE,
  BOOLEAN_TYPE,
  IDENTIFIER,
  FUNCTION,
  LPAREN, RPAREN,
  LBRACKET, RBRACKET,
  LBRACE, RBRACE,
  DOT, COLON,
  LT, GT, LTE, GTE, // <, >, <=, >=
  PLUS, MINUS,
  STAR, SLASH,
  CARAT, PERCENT,
  PLUS_EQUAL, MINUS_EQUAL,
  STAR_EQUAL, SLASH_EQUAL,
  CARAT_EQUAL, PERCENT_EQUAL,
  PLUS_PLUS, MINUS_MINUS,
  EQUAL, EQUAL_EQUAL,

  EOF
}

export default Syntax;